name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ clang clang-format

      - name: Check code style with clang-format
        run: |
          FILES=$(find library sample tests -name '*.cpp' -o -name '*.hpp' -o -name '*.h')
          for file in $FILES; do
            clang-format -style=file "$file" | diff "$file" -
          done

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Ninja" \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure
